services:
  overcrawlrr:
    image: ghcr.io/psyko-gh/overcrawlrr:develop
    container_name: overcrawlrr
    restart: unless-stopped
    ports:
      - 5056:5056
    environment:
      - TZ=Etc/UTC
      # OPTIONAL: the custom path to your settings file. Default: /config/settings.yaml
      # - CONFIG=/my/custom/config
    volumes:
      - /path/to/config:/config
