name: Contribution

on:
  pull_request:
    branches:
      - '*'

jobs:
  check:
    name: Lint & Test build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        env:
          HUSKY: 0
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Format
        run: npm run format
      - name: Docs format
        run: npm run format-docs
      - name: Build
        run: npm run build
      - name: Tests
        run: npm run test
      - name: Set commit status
        uses: myrotvorets/set-commit-status-action@master
        # Always run this even if previous steps fail
        if: always()
        with:
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.sha }}
